#!/usr/bin/env python
template = """/*
    ${CLASS}.vala
    Copyright (C) 2012 Maia Everett <maia@everett.one>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

namespace ${NS} {

public class ${CLASS} : GLib.Object {
	
}

}
"""

import string, sys

template = string.Template(template).substitute(NS = sys.argv[1], CLASS = sys.argv[2])

vfile = open('%s/%s.vala' % (sys.argv[1], sys.argv[2]), 'w')
vfile.write(template)
vfile.close()
